name: pyrpl-env
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - paramiko
  - pandas
  - nose
  - pip
  - pyqt
  - qtpy
  - pyqtgraph
  - pyyaml
  - python=3.7
  - ca-certificates
  - openssl
  - scp
